# Generated by Django 4.2.6 on 2023-11-02 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_list_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Olist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.list')),
            ],
        ),
    ]
