# Generated by Django 4.2.6 on 2023-11-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='tag',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='list',
            name='title',
        ),
        migrations.AddField(
            model_name='list',
            name='age',
            field=models.IntegerField(default=1),
        ),
    ]
