# Generated by Django 4.2.6 on 2023-11-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_tag_list_name_remove_list_title_list_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='address',
            field=models.CharField(default=250, max_length=250),
            preserve_default=False,
        ),
    ]
