# Generated by Django 4.2.6 on 2023-11-03 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_list_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 22, 30, 30, 209770)),
        ),
    ]
