# Generated by Django 4.2.6 on 2023-11-03 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_list_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='list',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 22, 35, 27, 969918)),
        ),
    ]
